"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getXataClient = exports.XataClient = void 0;
// Generated by Xata Codegen 0.29.4. Please do not edit.
const client_1 = require("@xata.io/client");
/** @typedef { import('./types').SchemaTables } SchemaTables */
/** @type { SchemaTables } */
const tables = [
  {
    name: "students",
    columns: [
      { name: "Student_Username", type: "string", unique: true },
      {
        name: "Student_PasswordHash",
        type: "text",
        notNull: true,
        defaultValue: "xxxxxxxx",
      },
      { name: "Student_Phone", type: "string", unique: true },
      { name: "Student_Email", type: "email", unique: true },
    ],
    revLinks: [
      { column: "StudentID", table: "applications" },
      { column: "StudentID", table: "student_registration" },
      { column: "StudentID", table: "student_documents" },
    ],
  },
  {
    name: "countries",
    columns: [
      { name: "Country", type: "string", notNull: true, defaultValue: "India" },
      {
        name: "Country_Description",
        type: "text",
        notNull: true,
        defaultValue: "xxxxxx",
      },
    ],
    revLinks: [{ column: "CountryID", table: "university_courses" }],
  },
  {
    name: "universities",
    columns: [
      { name: "University_Name", type: "string", unique: true },
      {
        name: "University_Location",
        type: "string",
        notNull: true,
        defaultValue: "Mumbai, Maharashtra",
      },
      {
        name: "University_Description",
        type: "text",
        notNull: true,
        defaultValue: "xxxxxxx",
      },
      { name: "University_Ranking", type: "int", unique: true },
      {
        name: "University_AdmissionProcess",
        type: "text",
        notNull: true,
        defaultValue: "xxxxxx",
      },
    ],
    revLinks: [{ column: "UniversityID", table: "university_courses" }],
  },
  {
    name: "university_courses",
    columns: [
      { name: "UniversityID", type: "link", link: { table: "universities" } },
      { name: "CountryID", type: "link", link: { table: "countries" } },
      {
        name: "Course_Name",
        type: "string",
        notNull: true,
        defaultValue: "Bachelor of Science in IT",
      },
      {
        name: "Course_Description",
        type: "text",
        notNull: true,
        defaultValue: "xxxxxxxx",
      },
      {
        name: "Course_Duration",
        type: "float",
        notNull: true,
        defaultValue: "4",
      },
      {
        name: "Course_Fees",
        type: "string",
        notNull: true,
        defaultValue: "200000",
      },
      {
        name: "Course_StartDate",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "Course_EndDate",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "Course_Status",
        type: "string",
        notNull: true,
        defaultValue: "Active",
      },
    ],
    revLinks: [{ column: "CourseID", table: "applications" }],
  },
  {
    name: "applications",
    columns: [
      { name: "CourseID", type: "link", link: { table: "university_courses" } },
      { name: "StudentID", type: "link", link: { table: "students" } },
      {
        name: "Application_Status",
        type: "string",
        notNull: true,
        defaultValue: "Pending",
      },
    ],
  },
  {
    name: "student_registration",
    columns: [
      { name: "StudentID", type: "link", link: { table: "students" } },
      {
        name: "Student_FirstName",
        type: "string",
        notNull: true,
        defaultValue: "User",
      },
      {
        name: "Student_LastName",
        type: "string",
        notNull: true,
        defaultValue: "User",
      },
      {
        name: "Student_DOB",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "Student_Address",
        type: "text",
        notNull: true,
        defaultValue: "India",
      },
      {
        name: "Student_ProfilePic",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
    ],
  },
  {
    name: "student_documents",
    columns: [
      { name: "StudentID", type: "link", link: { table: "students" } },
      {
        name: "Student_DocumentName",
        type: "string",
        notNull: true,
        defaultValue: "Adhaar Card",
      },
      {
        name: "Student_Document",
        type: "file[]",
        "file[]": { defaultPublicAccess: true },
      },
    ],
  },
];
/** @type { import('@xata.io/client').ClientConstructor<{}> } */
const DatabaseClient = (0, client_1.buildClient)();
const defaultOptions = {
  databaseURL:
    "https://appnichetechnologies-s-workspace-bbijnp.us-east-1.xata.sh/db/StudyWings",
};
/** @typedef { import('./types').DatabaseSchema } DatabaseSchema */
/** @extends DatabaseClient<DatabaseSchema> */
class XataClient extends DatabaseClient {
  constructor(options) {
    super({ ...defaultOptions, ...options }, tables);
  }
}
exports.XataClient = XataClient;
let instance = undefined;
/** @type { () => XataClient } */
const getXataClient = () => {
  if (instance) return instance;
  instance = new XataClient();
  return instance;
};
exports.getXataClient = getXataClient;
